name: Integration

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Check lint
        run: npm run lint
      - name: Check prettier
        run: npm run prettier
