name: Release

on:
  push:
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.3
      - name: Install dependencies
        run: npm i
      - name: Build app
        run: npm run build
      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: 'dist'
          target: '~/radio-rmi-player'
          rm: true
